Gelato using `execTransaction` for gas metering
safe-fndn/safe-modules pull request #326
Opened 2024-03-14 15:57 UTC by remedcu

This PR converts the gas metering check from using 4337 `EntryPoint v0.6` to using `execTransaction` directly in Safe.

Package Lock has been updated due to the addition of the Gelato relay kit package.

Closes #296

2024-03-15 14:22 UTC, akshay-ap requested changes

2024-03-15 14:22 UTC, akshay-ap commented on examples/4337-gas-metering/gelato/README.md
> +Appropriate calldata created.
Are all logs in the `README.md` needed?

Its better to keep only required information e.g. txhash, gas usage and remove other text. Perhaps, a table can be used if data is meant to be compared here.

2024-03-15 14:44 UTC, akshay-ap approved these changes

2024-03-19 06:42 UTC, nlordell approved these changes
Looks great. 

There are some linter warnings that would be nice to clean up, but that can be done in a follow up.

2024-03-19 08:27 UTC, merged